version: "3"

services:
    minecleb:
        container_name: minecleb
        image: itzg/minecraft-server
        ports:
          - '25565:25565'
          - '8123:8123'
        volumes: 
            - ./data:/data
        environment: 
            EULA: 'TRUE'
            TYPE: 'FORGE'
        privileged: true